volumes:
    postgres-data:
    redis-data:

services:
    postgres:
        image: postgres:16
        container_name: todo-list-pg
        restart: unless-stopped
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=todolist
            - POSTGRES_USER=todolist
            - POSTGRES_PASSWORD=todolist

    app:
        image: apollosoftwares/php:latest
        container_name: todo-list-php
        restart: unless-stopped
        working_dir: /var/www/app
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        volumes:
            - ./:/var/www/app
        links:
            - postgres
            - cache

    webserver:
        image: nginx:alpine
        container_name: todo-list-webserver
        restart: unless-stopped
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - 80:80
        links:
            - app
            - postgres
            - cache

    # Redis.
    cache:
        image: redis:5.0-alpine
        container_name: todo-list-redis
        restart: unless-stopped
        volumes:
            - redis-data:/data
        ports:
            - 6379:6379

    scheduler:
        build:
            context: .
            dockerfile: ./docker/scheduler/Dockerfile
        container_name: todo-list-scheduler
        working_dir: /var/www/app
        volumes:
        - .:/var/www/app
        restart: unless-stopped
        links:
        - webserver

    mailpit:
        image: axllent/mailpit
        restart: always
        ports:
        - 1025:1025
        - 8025:8025
